### ISSUE TITLE
Wishlist: Turn Slider direction for Rollershutters

### ISSUE THREAD

**Issue by HubertusH** [ghys/habpanel#1]
To use the Sliders in  combination with rollershutters it where helpfull to turn the direction to 0% on top and 100% to the bottom. Then the "blue" line correspond to the open/close state of the rollershutter.

**Comment by ghys** [comment]
Done in 335669461f7d248cb43b065fd330229fa9f92660

Empty your browser's cache if you don't see changes (save your configuration JSON object!) - working on a fix.
