### ISSUE TITLE
Prevent scrolling on iOS

### ISSUE THREAD

**Issue by neohusky** [ghys/habpanel#5]
It would be good to prevent scrolling (rubber band effect) when dragging your finger over the screen. This would help give the webpage an illusion of a true full screen app.

**Comment by ghys** [comment]
Please try checking out the https://github.com/ghys/habpanel/tree/ipad-overscolling-fix branch and see if it helps.

**Comment by neohusky** [comment]
Great work!!  I loaded it up on an ipad2 running iOS 9.3.5 and can confirm that there is **no more scrolling** when running through safari and also when saving it to the home screen and run in fullscreen mode.

Not that its a big deal for me, but, I tested it on my mac while copying the files over and scrolling is still present.  This may be a question for the community: This was obviously an iPad fix.  Would anyone have scrolling issues with other browsers/devices?

**Comment by ghys** [comment]
Ok, it's merged into master (#7). I'll close this for now. Chrome on Android has this pull-to-refresh feature I'd like to get rid of, and maybe desktop browser behave differently; they're related but separate issues. Thanks @neohusky for testing this out!

**Comment by kuifje123** [comment]
Just testing this, works great. It would be nice if scrolling can be enabled in edit mode only. Now it can happen that adding a new item is placed outside the viewing area, and cannot be moved therefore.

**Comment by neohusky** [comment]
Rather than enable scrolling conditionally if editing or viewing would it be better to try work on a fix that prevented items landing outside of the viewing area in the first place?
